<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Security\Voter\AuthorityVoter' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Security/Voter/AuthorityVoter.php';

return $this->privates['Eccube\\Security\\Voter\\AuthorityVoter'] = new \Eccube\Security\Voter\AuthorityVoter(($this->privates['Eccube\\Repository\\AuthorityRoleRepository'] ?? $this->load('getAuthorityRoleRepositoryService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))));
