<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Repository\BlockPositionRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Repository/BlockPositionRepository.php';

return $this->privates['Eccube\\Repository\\BlockPositionRepository'] = new \Eccube\Repository\BlockPositionRepository(($this->privates['Eccube\\Repository\\BlockRepository'] ?? $this->load('getBlockRepositoryService.php')), ($this->services['doctrine'] ?? $this->getDoctrineService()));
