<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Repository\BlockRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Repository/BlockRepository.php';

return $this->privates['Eccube\\Repository\\BlockRepository'] = new \Eccube\Repository\BlockRepository(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))));
