<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Request\Context' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Request/Context.php';

return $this->privates['Eccube\\Request\\Context'] = new \Eccube\Request\Context(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))), ($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()));
