<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'SunCat\MobileDetectBundle\DeviceDetector\MobileDetector' shared autowired service.

return $this->services['SunCat\\MobileDetectBundle\\DeviceDetector\\MobileDetector'] = new \SunCat\MobileDetectBundle\DeviceDetector\MobileDetector();
