<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Repository\PageRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Repository/PageRepository.php';

return $this->privates['Eccube\\Repository\\PageRepository'] = new \Eccube\Repository\PageRepository(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))), $this);
