<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Recommend4\Repository\RecommendProductRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/app/Plugin/Recommend4/Repository/RecommendProductRepository.php';

return $this->privates['Plugin\\Recommend4\\Repository\\RecommendProductRepository'] = new \Plugin\Recommend4\Repository\RecommendProductRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
