<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6QFDNEf\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6QFDNEf/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/Container6QFDNEf.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\Container6QFDNEf\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \Container6QFDNEf\EccubeEccube_KernelProdContainer([
    'container.build_hash' => '6QFDNEf',
    'container.build_id' => '6193fd4d',
    'container.build_time' => 1677136518,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6QFDNEf');
