<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\EventListener\ExceptionListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/EventListener/ExceptionListener.php';

return $this->privates['Eccube\\EventListener\\ExceptionListener'] = new \Eccube\EventListener\ExceptionListener(($this->services['twig'] ?? $this->getTwigService()), ($this->privates['Eccube\\Request\\Context'] ?? $this->getContextService()));
