<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SiteKit\Repository\IdTokenRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/app/Plugin/SiteKit/Repository/IdTokenRepository.php';

return $this->privates['Plugin\\SiteKit\\Repository\\IdTokenRepository'] = new \Plugin\SiteKit\Repository\IdTokenRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
